### ISSUE TITLE
Unable to access platform

### ISSUE THREAD

**Issue by thatguydan** [amphoradata/amphoradata.github.io#27]
Happy Friday! After login, all pages are displaying the below error, preventing access to the platform:

![image](https://user-images.githubusercontent.com/714300/94869581-fce71c80-0488-11eb-9271-1b9a30c35675.png)

Unable to say whether this is impacting just my account or others.

**Comment by xtellurian** [comment]
hm, that's a bad one!

I'm on it

**Comment by xtellurian** [comment]
I was seeing the same issue.  There was a problem validating the redirect URLs

@thatguydan can you try again, it's working for me now

**Comment by thatguydan** [comment]
Yep working for me!
