### ISSUE TITLE
uploading signals / capital letter issues

### ISSUE THREAD

**Issue by 1112114641** [amphoradata/amphoradata.github.io#6]
>Please Keep this section. Issue from 'appsvc62a56562.azurewebsites.net/Market'.

amphora python SDK

amphorae_upload_signal_batch successfully uploads signals if they are lower case. For an all caps signal string, no data will be added, yet a http 200 code is delivered, not an error.

**Comment by xtellurian** [comment]
Originally we limited the capitalisation of properties to prevent unnecessary duplication, however the validation wasn't being applied correctly.

We're deploying a fix in version `0.4.0`

From this version, all property names must only contain alphabetic characters and underscores, and must be between 3 and 20 characters long. This excludes the timestamp property, which remains "t". When uploading signal data to an amphora, you must match the property name exactly (including the case) or else the API will return an error.

Existing properties shouldn't be affected, but there may be some unexpected behaviour in the generated client SDKs when validating signal properties that were created before this restriction was applied.

The validating regex is below:
```
^[a-zA-Z_]{3,20}$
```

**Comment by xtellurian** [comment]
https://github.com/amphoradata/python-sdk/pull/3

**Comment by xtellurian** [comment]
This issue should now be resolved. 

For consistency, make sure you update your amphora data SDK to minimum version 0.4.0
