### ISSUE TITLE
in amphora 'view as grid' broken?

### ISSUE THREAD

**Issue by 1112114641** [amphoradata/amphoradata.github.io#7]
>Please Keep this section. Issue from 'appsvc62a56562.azurewebsites.net/Amphorae/Signals'.

when selected from the display menu, (where DL csv, drop marker, view grid) if view grid selected, a weird table is displayed on top of the displayed data, but not to scale.
possibly broken>?

**Comment by xtellurian** [comment]
@1112114641 which browser are you using?

In Google Chrome, when I click "Display Grid", I see the following overlaid on the graph.
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/8497130/71134440-71323580-2252-11ea-8c32-ffb56b05b0d2.png">

I believe this is the correct behaviour, although I do think `Display Grid` is perhaps the wrong wording. I don't think the entire table could be shown at once, but there's a scroll bar at the bottom.

**Comment by 1112114641** [comment]
Agreed, naming may be misleading. Overlaying an actual grid (in addition to markers?) might actually be helpful.
